### ISSUE TITLE
How is this extension different from Takashi Sugimoto?

### ISSUE THREAD

**Issue by kianweelee** [dharmeshtailor/chrome-extension---Access-Local-Files#1]
Hi, I was wondering whats the difference between your extension and [Takashi Sugimoto](https://github.com/tksugimoto/chrome-extension_open-local-file-link)?

**Comment by dharmeshtailor** [comment]
> Hi, I was wondering whats the difference between your extension and [Takashi Sugimoto](https://github.com/tksugimoto/chrome-extension_open-local-file-link)?

Original chrome extension only allowed to open the local links. I have modified the code to execute window.open from the frame access over cross domain.

This extension will be able to open the local windows folder as well.

**Comment by kianweelee** [comment]
Thats sweet. I was hoping for an extension for mac. Thanks anyways!
